package com.jopagima.school.commons.domain;

import java.util.UUID;

/**
 * Generic identifier value object, shared across bounded contexts via the commons
 * module. Backed by a real UUID — IDs are generated by the system, not supplied by
 * the client (breaking change vs. the plain-string ids used in Fase 1's
 * RegisterStudentRequest; the retroactive migration of students-service must adopt
 * the same contract change).
 */

public class Id {

    private final UUID value;
    
    private Id(UUID randomUUID) {
        this.value = randomUUID;
    }

    public static Id generateUniqueIdentifier() {
        return new Id(UUID.randomUUID());
    }

    public static Id generateFromPlainTextIdentifier(String plainText) {
        try {
            return new Id(UUID.fromString(plainText));
        } catch (IllegalArgumentException e) {
            throw ValidationError.create("Invalid UUID format.");
        }
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((value == null) ? 0 : value.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Id other = (Id) obj;
        if (value == null) {
            if (other.value != null)
                return false;
        } else if (!value.equals(other.value))
            return false;
        return true;
    }

    

    
}
